### ISSUE TITLE
Filemaker Go App and Square Register

### ISSUE THREAD

**Issue by ssamuel6** [square/SquareRegisterSDK-iOS#18]
Hi 
I'm trying to open the Square register app from my filemaker go app through the open url step 
and i can get to the square app
but from there im trying to get the call back url to a filemaker file hosted on filemaker server ...
do you know where i would need to specify that ?

**Comment by amberdixon** [comment]
Your filemaker iOS app needs to listen to a [custom URL scheme](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html) in order for Square Register to be able to talk to your app. Once you have implemented support for a custom URL scheme, please update the "Register API" section of your application settings in the [Square Developer Portal](https://connect.squareup.com/apps) with your URL scheme. For example, if your application will open for URLs that start with "filemaker://", then please put the string "filemaker" in the iOS URL scheme section of the Register API settings. Also specify the iOS bundle identifier of your filemaker app in the Square Developer Portal. Once your application is associated with a custom URL scheme, Register will open your app with the API response after it has completed the payment flow for a Register API request.
