### ISSUE TITLE
ErroDomain error 6

### ISSUE THREAD

**Issue by Rauleinstein** [square/SquareRegisterSDK-iOS#3]
Hello I'm triying to use this SDK but I'm getting an error 6 response when I get to the SquareApp. I can't find any documentation on this error. Can you give me more info?

**Comment by martinmroz** [comment]
Hi @Rauleinstein, thanks for your interest in the Square Register SDK!

I assume that the error domain you're seeing is the SCCAPIErrorDomain, is that right? If so, a code 6 corresponds to SCCAPIErrorCodeUserNotActivated. You can find additional information about this error message in our developer documentation here: https://docs.connect.squareup.com/api/register/#enum-sccapierrorcode -- let me know if there's anything else I can do to help!

I'll see what we can do about adding error code numbers to the API documentation.

**Comment by Rauleinstein** [comment]
Thank you very much, we found that our account was deactivated and we already fix it. It will very nice a better documentation on errors.

**Comment by martinmroz** [comment]
Any time!
