### ISSUE TITLE
Need a way of bypassing Receipt Screen in Square App.

### ISSUE THREAD

**Issue by raytetlow** [square/SquareRegisterSDK-iOS#7]
Need a parameter to the sdk call for a sale transaction (or in square app settings) that allows you to bypass the print receipt screen in the square app.  We are a POS app thats integrating with square - and we print our own receipts/email them etc.   In fact, we need to because they are a lot more complicated than the average receipt and are fully itemized.    Right now, the customer is confronted with two screens which is very confusing and we cannot get rid of ours - of course.

**Comment by amberdixon** [comment]
Hi there. We have a skip_receipt option that can be passed in the Register API request. It is documented here: https://docs.connect.squareup.com/articles/register-api-ios/
